### PR TITLE
Allow connecting to a server running in a subdirectory

### PR DESCRIPTION
**Pull request by immindich**
Provides a configuration option and a field in the login form to specify the server URL path, allowing the client to connect to a Mattermost server running in a subdirectory, as described in #538. This PR depends on matterhorn-chat/mattermost-api#48.

### CODE REVIEW

**Comment by glguy** [comment]
An alternative design would be to not separate the host and path portion but to allow the user to specify them all in one go. This has the advantage that the user can basically paste what he sees in a web browser into matterhorn. I'm imagining this UI:

```
          ┌──────────────────────────────────────────────────────────┐          
          │Please enter your Mattermost credentials to log in.       │          
          │                                                          │          
          │Server:           mattermost.example.com:443/path/part    │          
          │                                                          │                    │                                                          │          
          │Username:         emertens                                │          
          │                                                          │          
          │Password:                                                 │          
          │                                                          │          
          │          Press Enter to log in or Esc to exit.           │          
          └──────────────────────────────────────────────────────────┘
```

In the most common case where we use the defaults a user might only enter

```
          │Server:           mattermost.example.com                  │          
```

**Comment by jtdaugherty** [comment]
I like some aspects of that approach. For @immindich's clarity, though, I'd like to keep this PR focused on what's been changed so far and discuss/tackle @glguy's suggestion in another ticket or wiki page to work out the design.

**Comment by jtdaugherty** [comment]
@immindich FWIW I think this PR is ready to merge once the `mattermost-api` PR is merged. I know we discussed that PR in person last week and there were a few more next steps, but I don't remember what they were. Do you?

**Comment by immindich** [comment]
@jtdaugherty I believe the steps on the `mattermost-api` side were to add a bit more documentation (already mentioned in the pull request) and also do some URI validation in `initConnectionData`.

I would also need to update this PR to match any breaking changes from the above, and see if I want to do any form validation for server paths. I should have some time this afternoon to do this.

**Comment by jtdaugherty** [comment]
Thanks, @immindich!

**Pull request merged**
